import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApolloWrapper } from "@/lib/apollo-provider";
import { Toaster } from "@/components/ui/sonner";
import { NextAuthProvider } from "@/lib/next-auth-provider";

const kholic = localFont({
  src: "../assets/fonts/kholic.otf",
  variable: "--font-kholic",
  weight: "100 900",
});
const rafisqi = localFont({
  src: "../assets/fonts/Rafisqi Bold.ttf",
  variable: "--font-rafisqi",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tasty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <ApolloWrapper>
          <body
            className={`${kholic.variable} ${rafisqi.variable} antialiased font-Noto-Sans text-white`}
          >
            {children}
            <Toaster richColors />
          </body>
        </ApolloWrapper>
      </NextAuthProvider>
    </html>
  );
}
