import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ApolloClientProvider } from "@/lib/apollo-provider";
import { Toaster } from "@/components/ui/sonner";

const kholic = localFont({
  src: "../assets/fonts/kholic.otf",
  variable: "--font-kholic",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tasty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloClientProvider>
        <body
          className={`${kholic.variable} antialiased font-Noto-Sans text-white`}
        >
          {children}
          <Toaster richColors />
        </body>
      </ApolloClientProvider>
    </html>
  );
}
